"""Archive exact-job checkpoints and report coverage without double counting.

Run in Sage Docker. --restore RUN_DIRECTORY restores non-pair checkpoints from
its compact ledger; exact pair caches are regenerated by the search itself.
"""
import argparse
import gzip
import hashlib
import json
import os
from datetime import datetime,timezone
from pathlib import Path

HERE=Path(__file__).resolve().parent
RUNS=[HERE/'runs/exact-local-2026-09-10',HERE/'runs/exact-local-v2-2026-09-11']
TARGETED=HERE/'runs/exact-targeted-centers-2026-09-11'


def dump(path,data):
    tmp=path.with_suffix(path.suffix+'.tmp')
    tmp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    os.replace(tmp,path)


def load_records(run):
    files=sorted((run/'jobs').glob('*.json'))
    if files: return [json.loads(p.read_text()) for p in files]
    with gzip.open(run/'job-ledger.jsonl.gz','rt',encoding='utf-8') as stream:
        return [json.loads(line) for line in stream]


def archive(run,records):
    path=run/'job-ledger.jsonl.gz'; tmp=path.with_suffix('.tmp')
    with tmp.open('wb') as raw:
        with gzip.GzipFile(filename='',mode='wb',fileobj=raw,mtime=0) as stream:
            for record in sorted(records,key=lambda r:r['job']['id']):
                stream.write((json.dumps(record,ensure_ascii=False,separators=(',',':'))+'\n').encode())
    os.replace(tmp,path)
    return {'file':str(path.relative_to(HERE)),
      'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'records':len(records),'bytes':path.stat().st_size}


def stage(records):
    complete=[r for r in records if r['status']=='complete']
    durations=sorted(r['elapsed_ms'] for r in complete)
    return {'recorded_jobs':len(records),'complete':len(complete),
      'deferred':sum(r['status']=='deferred' for r in records),
      'errors':sum(r['status']=='error' for r in records),
      'tested_parameterizations_from_completed_jobs':sum(r.get('tested_parameterizations',0)+r.get('tested_terminal_parameterizations',0) for r in complete),
      'sum_recorded_worker_wall_ms':sum(r['elapsed_ms'] for r in records),
      'completed_job_median_ms':durations[len(durations)//2] if durations else None,
      'completed_job_p90_ms':durations[min(len(durations)-1,9*len(durations)//10)] if durations else None,
      'completed_job_max_ms':max(durations) if durations else None,
      'candidate_score_claims':[h['score'] for r in complete for h in r.get('hits',[])]}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--final',action='store_true')
    parser.add_argument('--restore',type=Path)
    args=parser.parse_args()
    if args.restore:
        run=args.restore.resolve(); jobs=run/'jobs'; jobs.mkdir(exist_ok=True)
        with gzip.open(run/'job-ledger.jsonl.gz','rt',encoding='utf-8') as stream:
            restored=0
            for line in stream:
                record=json.loads(line); job=record['job']; identifier=job['id']
                assert '/' not in identifier and '\\' not in identifier
                if job['phase']=='pair': continue
                path=jobs/(identifier+'.json')
                if not path.exists(): dump(path,record); restored+=1
        print(json.dumps({'restored_non_pair_jobs':restored,'run':str(run)})); return
    all_records=[]; run_reports=[]
    for run in RUNS+([TARGETED] if TARGETED.exists() else []):
        records=load_records(run); all_records.append(records)
        summary=json.loads((run/'summary.json').read_text())
        interrupted=run/'interrupted-summary.json'
        if interrupted.exists(): summary['status']='stopped_for_optimization'
        if args.final and summary['status']=='running': raise ValueError('Search is still running')
        run_reports.append({'run':str(run.relative_to(HERE)),'status':summary['status'],
          'manifest':json.loads((run/'manifest.json').read_text()),'ledger':archive(run,records),
          'stages':{phase:stage([r for r in records if r['job']['phase']==phase]) for phase in ('pair','one','two')}})
    merged={}
    for records in all_records:
        for r in records:
            if r['job']['phase']!='two': continue
            key=r['job']['id']
            if key not in merged or r['status']=='complete': merged[key]=r
    two=stage(list(merged.values()))
    two.update({'planned_first_object_parameterizations':8280,
      'not_recorded':8280-len(merged),'completed_skips':sum('skipped' in r and r['status']=='complete' for r in merged.values()),
      'deferred_is_not_excluded':True,
      'parameterizations_are_not_distinct_geometries':True})
    equivalence_path=RUNS[1]/'first-object-equivalence.json'
    equivalence=None
    if equivalence_path.exists():
        data=json.loads(equivalence_path.read_text())
        complete_ids={key for key,r in merged.items() if r['status']=='complete' and not r.get('hits')}
        excluded_groups=[g for g in data['groups'] if any(key in complete_ids for key in g)]
        indirect={key for g in excluded_groups for key in g if key not in complete_ids}
        equivalence={'distinct_first_objects':len(data['groups']),
          'objects_with_completed_representative':len(excluded_groups),
          'additional_parameterizations_excluded_by_exact_equality':len(indirect),
          'not_excluded_parameterizations':8280-len(complete_ids)-len(indirect),
          'report':str(equivalence_path.relative_to(HERE)),
          'additional_excluded_job_ids':sorted(indirect)}
    complementary={}
    for name in ('pair-geometry-summary.json','all-object-pairs-summary.json'):
        path=RUNS[1]/name
        if not path.exists(): continue
        data=json.loads(path.read_text()); rows=data.get('windows',data.get('pairs',[]))
        complementary[name]={'status':data['status'],'found':data['found'],'groups':len(rows),
          'complete_parameterizations':sum(r['complete_parameterizations'] for r in rows),
          'deferred':sum(r['deferred'] for r in rows),'elapsed_ms':data.get('elapsed_ms'),
          'scope':data['scope']}
    shorter_candidates=[{'job':r['job']['id'],**h} for r in merged.values() for h in r.get('hits',[]) if h['score']<=11]
    report={'status':'final' if args.final else 'snapshot','as_of_utc':datetime.now(timezone.utc).isoformat(),
      'authorized_wall_budget_seconds':3600,'scheduled_start_utc':'2026-09-10T15:50:18Z',
      'scheduled_finish_utc':'2026-09-10T16:50:18Z',
      'cpu_quota_phases':[{'from_utc':'2026-09-10T15:50:18Z','quota':4},
                          {'from_utc':'2026-09-10T16:30:20Z','quota':6}],
      'container_memory_limit_gib':5,
      'geometry':'Exact Sage AA/QQ/QQbar; no float geometry, tolerance, or approximate ranking.',
      'runs':run_reports,'two_step_union':two,'exact_equivalence_coverage':equivalence,
      'shorter_candidates_requiring_certificate_review':shorter_candidates,
      'complementary_searches':complementary,
      'conclusion':'Only the stated finite families and completed jobs are excluded. No global optimality claim.'}
    dump(HERE/'runs/hour-search-summary.json',report)
    print(json.dumps({'status':report['status'],'two_step_union':two,'shorter_candidates_requiring_certificate_review':shorter_candidates,
      'exact_equivalence_coverage':None if equivalence is None else {k:v for k,v in equivalence.items() if k!='additional_excluded_job_ids'},
      'complementary_searches':complementary},ensure_ascii=False,indent=2))


if __name__=='__main__': main()
